### ISSUE TITLE
How to pass multiple context in /api/v1/evaluate

### ISSUE THREAD

**Issue by sujith-es** [flipt-io/flipt-java#2]
Hi,

I am using Java to get the `/api/v1/evaluate` response. My request is as below 

```bash
{
  "flagKey": "feature-button-color",
  "entityId": 30cf230f-7997-4e3e-8c0b-cbf2fef1a011",
  "requestId": "feature-button-color-req-id",
  "context": {
    "isAdmin": "false",
    "email_address": "user_1@contoso.com",
    "environment":"prod"
  }
}
```

I have multiple contexts to pass but in the Java `EvaluationRequest` class I see the property as a String

```
  private final String context;
```

POM 
```
<dependency>
            <groupId>io.github.fern-api</groupId>
            <artifactId>flipt</artifactId>
            <version>0.1.1</version>
 </dependency>
```

Were as in [here ](https://github.com/flipt-io/flipt-java/blob/main/src/main/java/com/flipt/api/client/evaluate/types/EvaluationRequest.java#L26) I see it as Map
 and the fix in [0.1.6](https://github.com/flipt-io/flipt-java/commit/00a7b88abb040881a758da8c8971020f8c92e6a3?diff=split#diff-3a128867936310733ad9551599b2ae05f20b166d159232caf94dcc28c71a4745R54)
```
private final Map<String, String> context;
```

Am I using the correct POM version? `0.1.6` is not available in the maven repository?

**Comment by markphelps** [comment]
@sujith-es we just release `0.1.7` which should fix this. note: we are now published to our own repository in maven central so you'll need to update your `pom` to:

```xml
<dependency>
            <groupId>io.flipt</groupId>
            <artifactId>flipt-java</artifactId>
            <version>0.1.7</version>
 </dependency>
```

I updated the README as well: https://github.com/flipt-io/flipt-java

Please let us know if this resolves the issue!

**Comment by sujith-es** [comment]
@markphelps I have updated the pom version and the issue is fixed. Thank you for the update.
