### ISSUE TITLE
Unable to get feature flag since upgrading to 0.2.0

### ISSUE THREAD

**Issue by marcus-bcl** [flipt-io/flipt-java#4]
After upgrading from 0.1.8 to 0.2.0, getting the value of a feature flag is failing.

The error is in `FlagsClientImpl.get`, as it's attempting to pass a request body to a GET call, which okhttp rejects: https://github.com/flipt-io/flipt-java/blob/eb35b840c9bdb48809ed1763edd372906e91cd41/src/main/java/com/flipt/api/resources/flags/FlagsClientImpl.java#L102

Stack trace:
```
java.lang.IllegalArgumentException: method GET must not have a request body.
	at okhttp3.Request$Builder.method(Request.kt:258) ~[okhttp-4.10.0.jar:na]
	at com.flipt.api.resources.flags.FlagsClientImpl.get(FlagsClientImpl.java:102) ~[flipt-java-0.2.0.jar:na]
	...
```

**Comment by markphelps** [comment]
Thanks @marcus-bcl for the bug report and apologies for bug. We will work to get this fixed today!

**Comment by markphelps** [comment]
@marcus-bcl This should be fixed now https://github.com/flipt-io/flipt-java/releases/tag/0.2.2

Please let me know if the issue persists

**Comment by marcus-bcl** [comment]
Thanks @markphelps.  Could I ask a slightly unrelated question, is the latest version of the API client backwards-compatible with the Flipt 1.19 API?

**Comment by marcus-bcl** [comment]
> is the latest version of the API client backwards-compatible with the Flipt 1.19 API?
Scratch that, I gave it a try and it looks like the client is not backwards-compatible with the older API, as it uses the new namespaces endpoint.  However the Flipt 1.20 API is backward-compatible with the older client.  So I'd need to upgrade Flipt first, then the client.

**Comment by markphelps** [comment]
Closing as completed by https://github.com/flipt-io/flipt-java/releases/tag/0.2.2
